defmodule SunporchWeb.OnboardingGuidelinesLive do
  use SunporchWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    user = socket.assigns.current_user

    if user.onboarding_completed_at do
      {:ok, push_navigate(socket, to: "/feed")}
    else
      {:ok,
       socket
       |> assign(:page_title, "Community Guidelines")
       |> assign(:agreed, false)}
    end
  end

  @impl true
  def handle_event("toggle_agree", _params, socket) do
    {:noreply, assign(socket, :agreed, !socket.assigns.agreed)}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="single-column" style="max-width: 600px; margin: 0 auto;">
      <div class="onboarding-progress">
        <div class="onboarding-steps">
          <span class="onboarding-step completed">1. Welcome</span>
          <span class="onboarding-step-separator">&rarr;</span>
          <span class="onboarding-step active">2. Guidelines</span>
          <span class="onboarding-step-separator">&rarr;</span>
          <span class="onboarding-step">3. Privacy</span>
          <span class="onboarding-step-separator">&rarr;</span>
          <span class="onboarding-step">4. Profile</span>
        </div>
        <div class="onboarding-step-label">Step 2 of 4</div>
      </div>

      <div class="content-box-padded">
        <h1 style="font-size: 18px; font-weight: bold; color: #3b5998; margin-bottom: 12px;">
          Community Guidelines
        </h1>

        <p style="font-size: 11px; color: #333; line-height: 1.5; margin-bottom: 12px;">
          Sunporch is a community of real people. To keep it that way, we ask
          everyone to follow these guidelines.
        </p>

        <div class="sidebar-box" style="margin-bottom: 10px;">
          <div class="sidebar-box-header">Be Authentic</div>
          <div class="sidebar-box-content" style="font-size: 11px; line-height: 1.5;">
            Use your real name and identity. Sunporch is for genuine human interaction.
            Fake accounts, bots, and impersonation are not allowed.
          </div>
        </div>

        <div class="sidebar-box" style="margin-bottom: 10px;">
          <div class="sidebar-box-header">No AI-Generated Content</div>
          <div class="sidebar-box-content" style="font-size: 11px; line-height: 1.5;">
            All posts, comments, messages, and images must be created by you -- a real
            human being. Content generated by ChatGPT, Midjourney, DALL-E, or any other
            AI tool is not permitted. This is the core principle of Sunporch.
          </div>
        </div>

        <div class="sidebar-box" style="margin-bottom: 10px;">
          <div class="sidebar-box-header">Respect Privacy</div>
          <div class="sidebar-box-content" style="font-size: 11px; line-height: 1.5;">
            Do not share other people's personal information without their consent.
            Respect the privacy settings that others have chosen. Do not screenshot
            or redistribute private content.
          </div>
        </div>

        <div class="sidebar-box" style="margin-bottom: 10px;">
          <div class="sidebar-box-header">Be Kind</div>
          <div class="sidebar-box-content" style="font-size: 11px; line-height: 1.5;">
            Treat others with respect. Harassment, hate speech, bullying, and threats
            are not tolerated. Disagree respectfully. Remember there is a real person
            on the other side of the screen.
          </div>
        </div>

        <div class="alert alert-info" style="font-size: 11px; margin-bottom: 12px;">
          <strong>About AI Detection:</strong>
          Content you post may be scanned by AI detection systems to ensure it was
          human-written. If your content is flagged, you will be notified and can
          submit an appeal. Moderators review all appeals fairly.
        </div>

        <div class="form-check" style="margin-bottom: 12px;">
          <input
            type="checkbox"
            id="agree-guidelines"
            checked={@agreed}
            phx-click="toggle_agree"
          />
          <label for="agree-guidelines" style="font-size: 11px;">
            I have read and agree to these community guidelines
          </label>
        </div>

        <div class="form-actions" style="justify-content: space-between;">
          <a href="/onboarding/welcome" class="btn btn-gray">
            &larr; Back
          </a>
          <a
            href={if @agreed, do: "/onboarding/privacy", else: "#"}
            class={"btn btn-blue #{unless @agreed, do: "disabled"}"}
          >
            Next &rarr;
          </a>
        </div>
      </div>
    </div>
    """
  end
end
